apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: digidocs-app
  namespace: default
spec:
  dnsNames:
    - stage.digidocs.one
  secretName: digidocs-app-tls
  issuerRef:
    name: letsencrypt-cluster-issuer
    kind: ClusterIssuer