apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
        - name: auth
          image: digidocs/auth
          env:
            - name: MONGO_URI
              value: 'mongodb://mongo-srv/auth'

            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_KEY

            - name: ACCESS_TOKEN_EXP
              valueFrom:
                secretKeyRef:
                  name: access-token-exp
                  key: ACCESS_TOKEN_EXP

            - name: REFRESH_TOKEN_SECRET
              valueFrom:
                secretKeyRef:
                  name: refresh-token-secret
                  key: REFRESH_TOKEN_SECRET

            - name: REFRESH_TOKEN_EXP
              valueFrom:
                secretKeyRef:
                  name: refresh-token-exp
                  key: REFRESH_TOKEN_EXP

            - name: TIME_BASED_TOKEN_SECRET
              valueFrom:
                secretKeyRef:
                  name: time-based-token-secret
                  key: TIME_BASED_TOKEN_SECRET
---
apiVersion: v1
kind: Service
metadata:
  name: auth-srv
spec:
  selector:
    app: auth
  ports:
    - name: auth
      protocol: TCP
      port: 3000
      targetPort: 3000