apiVersion: apps/v1
kind: Deployment
metadata:
  name: document-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: document
  template:
    metadata:
      labels:
        app: document
    spec:
      containers:
        - name: document
          image: digidocs/document
          env:
            - name: MONGO_URI
              value: mongodb://host.docker.internal/document

            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name 

            - name: NATS_URI
              value: 'http://nats-srv:4222'

            - name: NATS_CLUSTER_ID
              value: digidocs

            - name: ACCESS_TOKEN_SECRET
              valueFrom:
                secretKeyRef:
                  name: access-token-secret
                  key: ACCESS_TOKEN_SECRET
---
apiVersion: v1
kind: Service
metadata:
  name: document-srv
spec:
  selector:
    app: document
  ports:
    - name: document
      protocol: TCP
      port: 3000
      targetPort: 3000