apiVersion: skaffold/v2alpha3
kind: Config
deploy:
  kubectl:
    manifests:
      - ../../k8s/k8s-dev/*
build:
  local:
    push: false
  artifacts:
    - image: digidocs/auth
      context: ../../
      docker:
        dockerfile: ./auth/Dockerfile
      sync:
        manual:
          - src: 'src/***/*.ts'
            dest: .
    - image: digidocs/authorization
      context: ../../
      docker:
        dockerfile: ./authorization/Dockerfile
      sync:
        manual:
          - src: 'src/***/*.ts'
            dest: .
    - image: digidocs/email
      context: ../../
      docker:
        dockerfile: ./email/Dockerfile
      sync:
        manual:
          - src: 'src/***/*.ts'
            dest: .
    - image: digidocs/document
      context: ../../
      docker:
        dockerfile: ./document/Dockerfile
      sync:
        manual:
          - src: 'src/***/*.ts'
            dest: .
    - image: digidocs/signing
      context: ../../
      docker:
        dockerfile: ./signing/Dockerfile
      sync:
        manual:
          - src: 'src/***/*.ts'
            dest: .
