apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: digidocs-app
  namespace: default
spec:
  dnsNames:
    - api.digidocs.one
    - kong-admin.digidocs.one
  secretName: digidocs-app-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
