apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: example-app
  namespace: default
spec:
  dnsNames:
    - api.example.com
  secretName: example
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
