apiVersion: apps/v1
kind: Deployment
metadata:
  name: document-service-depl
spec:
  replicas: 2
  selector:
    matchLabels:
      app: document
  template:
    metadata:
      labels:
        app: document
    spec:
      containers:
        - name: document
          image: asia.gcr.io/digidocs-stage/document:latest
          env:
            - name: PORT
              value: '80'

            - name: MONGO_URI
              value: mongodb+srv://admin:FTPSX3tKzXqdfhXE@digidocs-cluster1.mpdbe.mongodb.net/documentdb

            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name

            - name: NATS_URI
              value: 'http://nats-srv:4222'

            - name: NATS_CLUSTER_ID
              value: 'digidocs'

            - name: ACCESS_TOKEN_SECRET
              valueFrom:
                secretKeyRef:
                  name: access-token-secret
                  key: ACCESS_TOKEN_SECRET

            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: aws-access-key-id
                  key: AWS_ACCESS_KEY_ID

            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: aws-secret-access-key
                  key: AWS_SECRET_ACCESS_KEY

            - name: ENCRYPTION_SECRET
              valueFrom:
                secretKeyRef:
                  name: encryption-secret
                  key: ENCRYPTION_SECRET

            - name: DOCUMENT_ACCESS_URL
              valueFrom:
                secretKeyRef:
                  name: document-access-url
                  key: DOCUMENT_ACCESS_URL

            - name: FILE_KEY
              valueFrom:
                secretKeyRef:
                  name: file-key
                  key: FILE_KEY

            - name: CLOUDFRONT_URI
              value: 'https://digidocs-local-bucket.s3.ap-south-1.amazonaws.com'

            - name: AWS_S3_BUCKET
              value: 'digidocs-local-bucket'

            - name: ESIGN_SERVICE_BASE_URL
              value: 'http://signing-srv'

            - name: PAYMENT_SERVICE_BASE_URL
              value: 'https://stage-api.digidocs.one/api/v1'

            - name: PAYMENT_CALLBACK_URL
              value: 'https://stage-api.digidocs.one/api/v1/document/orders/payment/callback'
---
apiVersion: v1
kind: Service
metadata:
  name: document-srv
spec:
  selector:
    app: document
  ports:
    - name: document
      protocol: TCP
      port: 80
      targetPort: 80
