apiVersion: apps/v1
kind: Deployment
metadata:
  name: email-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: email
  template:
    metadata:
      labels:
        app: email
    spec:
      containers:
        - name: email
          image: asia.gcr.io/earnest-reactor-324513/email
          env:
            - name: NODEMAILER_EMAIL
              value: 'notifications@digidocsapp.com'

            - name: NODEMAILER_PASS
              value: 'notifications@12345'

            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name 

            - name: NATS_URI
              value: 'http://nats-srv:4222'

            - name: NATS_CLUSTER_ID
              value: digidocs