apiVersion: skaffold/v2alpha3
kind: Config
deploy:
  kubectl:
    manifests:
      - ../../k8s/k8s-prod/*
build:
  # local:
  #   push: false
  googleCloudBuild:
    projectId: earnest-reactor-324513
  artifacts:
    - image: asia.gcr.io/earnest-reactor-324513/auth
      context: ../../
      docker:
        dockerfile: ./auth/Dockerfile
      sync:
        manual:
          - src: 'src/***/*.ts'
            dest: .
    - image: asia.gcr.io/earnest-reactor-324513/email
      context: ../../
      docker:
        dockerfile: ./email/Dockerfile
      sync:
        manual:
          - src: 'src/***/*.ts'
            dest: .
    - image: asia.gcr.io/earnest-reactor-324513/document
      context: ../../
      docker:
        dockerfile: ./document/Dockerfile
      sync:
        manual:
          - src: 'src/***/*.ts'
            dest: .
    - image: asia.gcr.io/earnest-reactor-324513/signing
      context: ../../
      docker:
        dockerfile: ./signing/Dockerfile
      sync:
        manual:
          - src: 'src/***/*.ts'
            dest: .