apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
        - name: auth
          image: asia.gcr.io/digidocs-stage/auth:latest
          env:
            - name: PORT
              value: "80"

            - name: MONGO_URI
              valueFrom:
                secretKeyRef:
                  name: auth-mongo-uri
                  key: AUTH_MONGO_URI

            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name

            - name: NATS_URI
              value: "http://nats-srv:4222"

            - name: NATS_CLUSTER_ID
              value: "digidocs"

            - name: ACCESS_TOKEN_SECRET
              valueFrom:
                secretKeyRef:
                  name: access-token-secret
                  key: ACCESS_TOKEN_SECRET

            - name: ACCESS_TOKEN_EXP
              valueFrom:
                secretKeyRef:
                  name: access-token-exp
                  key: ACCESS_TOKEN_EXP

            - name: REFRESH_TOKEN_SECRET
              valueFrom:
                secretKeyRef:
                  name: refresh-token-secret
                  key: REFRESH_TOKEN_SECRET

            - name: REFRESH_TOKEN_EXP
              valueFrom:
                secretKeyRef:
                  name: refresh-token-exp
                  key: REFRESH_TOKEN_EXP

            - name: TIME_BASED_TOKEN_SECRET
              valueFrom:
                secretKeyRef:
                  name: time-based-token-secret
                  key: TIME_BASED_TOKEN_SECRET

            - name: GOOGLE_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: google-client-id
                  key: GOOGLE_CLIENT_ID

            - name: GOOGLE_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: google-client-secret
                  key: GOOGLE_CLIENT_SECRET

            - name: CLIENT_URL
              valueFrom:
                secretKeyRef:
                  name: client-url
                  key: CLIENT_URL

            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: aws-access-key-id
                  key: AWS_ACCESS_KEY_ID

            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: aws-secret-access-key
                  key: AWS_SECRET_ACCESS_KEY

            - name: CLOUDFRONT_URI
              value: ""

            - name: AWS_S3_BUCKET
              value: ""
---
apiVersion: v1
kind: Service
metadata:
  name: auth-srv
spec:
  selector:
    app: auth
  ports:
    - name: auth
      protocol: TCP
      port: 80
      targetPort: 80
