apiVersion: apps/v1
kind: Deployment
metadata:
  name: nato-service-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nato
  template:
    metadata:
      labels:
        app: nato
    spec:
      containers:
        - name: nato
          image: asia.gcr.io/digidocs-stage/nato-service:latest
          env:
            - name: PORT
              value: "80"

            - name: MONGO_URI
              valueFrom:
                secretKeyRef:
                  name: nato-mongo-uri
                  key: NATO_MONGO_URI

            - name: NODEMAILER_EMAIL
              value: "notifications@digidocs.one"

            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name

            - name: URL_SHORTENER_BASE_URL
              value: "https://di-gi.in/"

            - name: NATS_URI
              value: "http://nats-srv:4222"

            - name: NATS_CLUSTER_ID
              value: "digidocs"
---
apiVersion: v1
kind: Service
metadata:
  name: nato-srv
spec:
  selector:
    app: nato
  ports:
    - name: nato
      protocol: TCP
      port: 80
      targetPort: 80
