apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment
  template:
    metadata:
      labels:
        app: payment
    spec:
      containers:
        - name: payment
          image: asia.gcr.io/digidocs-stage/payment:latest
          env:
            - name: PORT
              value: '80'

            - name: MONGO_URI
              valueFrom:
                secretKeyRef:
                  name: payment-mongo-uri
                  key: PAYMENT_MONGO_URI

            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name

            - name: NATS_URI
              value: 'http://nats-srv:4222'

            - name: NATS_CLUSTER_ID
              value: 'digidocs'

            - name: PAYMENT_SIGNING_SALT
              valueFrom:
                secretKeyRef:
                  name: payment-signing-salt
                  key: PAYMENT_SIGNING_SALT

            - name: CCAVENUE_MERCHANT_ID
              valueFrom:
                secretKeyRef:
                  name: ccavenue-merchant-id
                  key: CCAVENUE_MERCHANT_ID

            - name: CCAVENUE_WORKING_KEY
              valueFrom:
                secretKeyRef:
                  name: ccavenue-working-key
                  key: CCAVENUE_WORKING_KEY

            - name: CCAVENUE_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: ccavenue-access-key
                  key: CCAVENUE_ACCESS_KEY

            - name: PAYMENT_SALT_EXPIRE
              valueFrom:
                secretKeyRef:
                  name: payment-salt-expire
                  key: PAYMENT_SALT_EXPIRE

            - name: CCAVENUE_STAGE_URL
              value: https://test.ccavenue.com/transaction/transaction.do?command=initiateTransaction

            - name: PAYMENT_CALLBACK
              value: https://stage-api.digidocs.one/api/v1/orders/payments/callback

---
apiVersion: v1
kind: Service
metadata:
  name: payment-srv
spec:
  selector:
    app: payment
  ports:
    - name: payment
      protocol: TCP
      port: 80
      targetPort: 80
