apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-srv
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  rules:
    - host: digidocs.dev
      http:
        paths:
          - path: /api/auth/?(.*)
            pathType: Prefix
            backend:
              service: 
                name: auth-srv
                port: 
                  number: 3000
          - path: /api/document/?(.*)
            pathType: Prefix
            backend:
              service: 
                name: document-srv
                port: 
                  number: 3000
          - path: /api/esign/?(.*)
            pathType: Prefix
            backend:
              service: 
                name: signing-srv
                port: 
                  number: 3000