name: Auth deployment

on:
  push:
    branches:
      - master
    paths:
      - 'auth/**'
      - 'guardian/**'
  workflow_dispatch:

env:
  PROJECT_ID: digidocs-stage
  GKE_ZONE: asia-south1-b
  IMAGE: auth

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2

      # Setup GCR
      job:
        job_id:
          steps:
            - id: 'auth'
              uses: 'google-github-actions/auth@v0.8.0'
              with:
                credentials_json: '${{ secrets.GCR_SERVICE_JSON }}'

            - name: 'Set up Cloud SDK'
              uses: 'google-github-actions/setup-gcloud@v0.6.0'

      - run: gcloud --quiet auth configure-docker

      - name: Build image
        run: docker build -t asia.gcr.io/$PROJECT_ID/$IMAGE -f $IMAGE/Dockerfile .
      - name: Push image
        run: docker push asia.gcr.io/$PROJECT_ID/$IMAGE

      # Digital Ocean Setup and deployment
      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      - name: Config kubernetes
        run: doctl kubernetes cluster kubeconfig save digidocs-stage-cluster
      - name: Restart deployment
        run: kubectl rollout restart deployment $IMAGE-depl
