name: Manifest deployment

on:
  push:
    branches:
      - master
    paths:
      - 'infra/k8s-prod/**'
  workflow_dispatch:

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2
      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      - name: Config kubernetes
        run: doctl kubernetes cluster kubeconfig save kongqa-stage-cluster
      - name: Apply infra
        run: kubectl apply -f infra/k8s-prod/deployments-manager
