name: Manifest deployment

on:
  push:
    branches:
      - master
    paths:
      - 'infra/k8s/k8s-prod/**'
jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo 
        uses: actions/checkout@v2
      - name: Install doctl 
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      - name: Config kubernetes
        run: doctl kubernetes cluster kubeconfig save digidocs-stage-cluster
        run: kubectl apply --validate=false -f infra/k8s/k8s-prod/cert-manager/cert-manager-1.5.3.yaml
        run: kubectl apply -f infra/k8s/k8s-prod
        