name: document deployment

on:
  push:
    branches:
      - master
    paths:
      - 'document-service/**'
      - 'guardian/**'
  workflow_dispatch:

env:
  PROJECT_ID: digidocs-stage
  GKE_ZONE: asia-south1-b
  IMAGE: document-service

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2

      # Setup GCR
      - uses: google-github-actions/setup-gcloud@v0.3.0
        with:
          service_account_key: ${{ secrets.GCR_KEY }}
          project_id: ${{ secrets.GKE_PROJECT }}

      - run: gcloud --quiet auth configure-docker

      - name: Build image
        run: docker build -t asia.gcr.io/$PROJECT_ID/$IMAGE -f $IMAGE/Dockerfile .
      - name: Push image
        run: docker push asia.gcr.io/$PROJECT_ID/$IMAGE

      # Digital Ocean Setup and deployment
      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      - name: Config kubernetes
        run: doctl kubernetes cluster kubeconfig save digidocs-stage-cluster
      - name: Restart deployment
        run: kubectl rollout restart deployment $IMAGE-depl
