name: Document deployment

on:
  push:
    branches:
      - master
    paths:
      - 'document/**'
  workflow_dispatch:
 
jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo 
        uses: actions/checkout@v2
      - name: Build image 
        run: cd document && docker build -t digidocs/document .
      - name: Install doctl 
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      - name: Log in to Container Registry 
        run: doctl registry login --expiry-seconds 600
      - name: Tag image 
        run:
          docker tag digidocs/document \
          registry.digitalocean.com/digidocs-stage-container/document:latest
      - name: Push image to Container Registry 
        run: docker push registry.digitalocean.com/digidocs-stage-container/document:latest
      - name: Config kubernetes
        run: doctl kubernetes cluster kubeconfig save digidocs-stage-cluster
      - name: Restart deployment
        run: kubectl rollout restart deployment document-depl